### PR TITLE
Restyaboard Stackscript

### PR DESCRIPTION
**Pull request by sridhar391**
Restyaboard is an open source alternative to Trello, but with smart additional features like offline sync, diff /revisions, nested comments, multiple view layouts, chat, and more. And since it is self-hosted, data, privacy, and IP security can be guaranteed.

### CODE REVIEW

**Comment by hmorris3293** [comment]
Hi @sridhar391 Thank you for your submission! I've tested this stackscript out and I'm not able to see anything listening on port 80 or 443, so I wasn't able to visit the IP and see the Restyaboard dashboard. Can you please confirm if the installation script is working as expected for you? 
For reference, I've tested this on Ubuntu 20.04 & Debian 10 and both failed. Here is the only noticeable error I can see in the script logs:

`* SSL certificate problem: unable to get local issuer certificate
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
`

**Comment by sridhar391** [comment]
@hmorris3293 Fixed the issue and tested the installation script and it is working correctly and after deploying the linode, all the Restyaboard dependant softwares will be installed and the Restyaboard will be loaded while loading the linode IP Address

**Comment by hmorris3293** [comment]
@sridhar391  confirmed, app is looking good 👍 
The last part of the submission here that is missing is the documentation piece for your Marketplace apps. You can find and example of what you'll need to include in the link below:

https://github.com/linode/docs/blob/develop/docs/guides/platform/marketplace/harbor-marketplace-app/index.md

If you have any questions, please feel free to reach out

**Comment by sridhar391** [comment]
@hmorris3293 We have added the documentation for Restyaboard Marketplace app in https://github.com/sridhar391/Marketplace-Apps/blob/master/restyaboard/template.md and we have also added the documentation for Restyaboard in the link https://restya.com/board/docs/install-restyaboard-linode-marketplace-tutorial/

**Comment by sridhar391** [comment]
@hmorris3293 We have added the documentation link for Restyaboard Marketplace app in https://github.com/sridhar391/Marketplace-Apps/blob/master/restyaboard/template.md and we have also added the documentation for Restyaboard in the link https://restya.com/board/docs/install-restyaboard-linode-marketplace-tutorial/

**Pull request merged**
