### PR TITLE
add cyberpanel

### PR DESCRIPTION
**Pull request by Code-Egg**

### CODE REVIEW

**Comment by rylabs-billy** [comment]
Hi @Code-Egg ,

I logged the script outputs and seeing some errors that question if all components of the panel will be functional as needed after install. Can you take a look and make sure these don't prevent some features from working as intended?

```
# ubuntu 18.04
##############
...
[12.22.2020_15-45-11] Running groupadd docker failed. Running again, try number 1
[12.22.2020_15-45-11] Running groupadd docker failed. Running again, try number 2
[12.22.2020_15-45-11] Running groupadd docker failed. Running again, try number 3
[12.22.2020_15-45-11] [ERROR] We are not able to run groupadd docker return code: 9.
...
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO).
error encountered creating user:
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
dbconfig-common: pdns-backend-mysql configure: ignoring errors from here forwards
/etc/aliases does not exist, creating it.
WARNING: /etc/aliases exists, but does not have a root alias.
[12.22.2020_15-48-33] Running apt-get -y debconf-utils failed. Running again, try number 1
[12.22.2020_15-48-33] Running apt-get -y debconf-utils failed. Running again, try number 2
[12.22.2020_15-48-33] Running apt-get -y debconf-utils failed. Running again, try number 3
[12.22.2020_15-48-33] [ERROR] We are not able to run apt-get -y debconf-utils return code: 100.
...
[12.22.2020_15-50-56] Running chown -R lscpd:lscpd /usr/local/CyberCP/public/phpmyadmin failed. Running again, try number 1
[12.22.2020_15-50-56] Running chown -R lscpd:lscpd /usr/local/CyberCP/public/phpmyadmin failed. Running again, try number 2
[12.22.2020_15-50-56] Running chown -R lscpd:lscpd /usr/local/CyberCP/public/phpmyadmin failed. Running again, try number 3
[12.22.2020_15-50-56] [ERROR] We are not able to run chown -R lscpd:lscpd /usr/local/CyberCP/public/phpmyadmin return code: 1.
...
[12.22.2020_15-51-33] Running usermod -G lscpd,lsadm,nobody lscpd failed. Running again, try number 1
[12.22.2020_15-51-33] Running usermod -G lscpd,lsadm,nobody lscpd failed. Running again, try number 2
[12.22.2020_15-51-33] Running usermod -G lscpd,lsadm,nobody lscpd failed. Running again, try number 3
[12.22.2020_15-51-33] [ERROR] We are not able to run usermod -G lscpd,lsadm,nobody lscpd return code: 6.
[12.22.2020_15-51-43] Running chmod 644 /etc/yum.repos.d/MariaDB.repo failed. Running again, try number 1
[12.22.2020_15-51-43] Running chmod 644 /etc/yum.repos.d/MariaDB.repo failed. Running again, try number 2
[12.22.2020_15-51-43] Running chmod 644 /etc/yum.repos.d/MariaDB.repo failed. Running again, try number 3
[12.22.2020_15-51-43] [ERROR] We are not able to run chmod 644 /etc/yum.repos.d/MariaDB.repo return code: 1.
[12.22.2020_15-51-43] Running chmod 644 /etc/pdns/pdns.conf failed. Running again, try number 1
[12.22.2020_15-51-43] Running chmod 644 /etc/pdns/pdns.conf failed. Running again, try number 2
[12.22.2020_15-51-43] Running chmod 644 /etc/pdns/pdns.conf failed. Running again, try number 3
[12.22.2020_15-51-43] [ERROR] We are not able to run chmod 644 /etc/pdns/pdns.conf return code: 1.
[12.22.2020_15-51-43] Running chmod 644 /usr/local/lsws/conf/httpd_config.xml failed. Running again, try number 1
[12.22.2020_15-51-43] Running chmod 644 /usr/local/lsws/conf/httpd_config.xml failed. Running again, try number 2
[12.22.2020_15-51-43] Running chmod 644 /usr/local/lsws/conf/httpd_config.xml failed. Running again, try number 3
[12.22.2020_15-51-43] [ERROR] We are not able to run chmod 644 /usr/local/lsws/conf/httpd_config.xml return code: 1.
[12.22.2020_15-51-43] Running chmod 644 /usr/local/lsws/conf/modsec.conf failed. Running again, try number 1
[12.22.2020_15-51-43] Running chmod 644 /usr/local/lsws/conf/modsec.conf failed. Running again, try number 2
[12.22.2020_15-51-43] Running chmod 644 /usr/local/lsws/conf/modsec.conf failed. Running again, try number 3
[12.22.2020_15-51-43] [ERROR] We are not able to run chmod 644 /usr/local/lsws/conf/modsec.conf return code: 1.
[12.22.2020_15-51-43] Running chmod 644 /usr/local/lsws/conf/httpd.conf failed. Running again, try number 1
[12.22.2020_15-51-43] Running chmod 644 /usr/local/lsws/conf/httpd.conf failed. Running again, try number 2
[12.22.2020_15-51-43] Running chmod 644 /usr/local/lsws/conf/httpd.conf failed. Running again, try number 3
[12.22.2020_15-51-43] [ERROR] We are not able to run chmod 644 /usr/local/lsws/conf/httpd.conf return code: 1.
[12.22.2020_15-51-43] Running chmod 600 /etc/pdns/pdns.conf failed. Running again, try number 1
[12.22.2020_15-51-43] Running chmod 600 /etc/pdns/pdns.conf failed. Running again, try number 2
[12.22.2020_15-51-43] Running chmod 600 /etc/pdns/pdns.conf failed. Running again, try number 3
[12.22.2020_15-51-43] [ERROR] We are not able to run chmod 600 /etc/pdns/pdns.conf return code: 1.
[12.22.2020_15-51-43] Running chmod 600 /etc/cagefs/exclude/cyberpanelexclude failed. Running again, try number 1
[12.22.2020_15-51-43] Running chmod 600 /etc/cagefs/exclude/cyberpanelexclude failed. Running again, try number 2
[12.22.2020_15-51-43] Running chmod 600 /etc/cagefs/exclude/cyberpanelexclude failed. Running again, try number 3
[12.22.2020_15-51-43] [ERROR] We are not able to run chmod 600 /etc/cagefs/exclude/cyberpanelexclude return code: 1.
[12.22.2020_15-51-43] Running chmod 640 /usr/local/lscp/cyberpanel/logs/access.log failed. Running again, try number 1
[12.22.2020_15-51-43] Running chmod 640 /usr/local/lscp/cyberpanel/logs/access.log failed. Running again, try number 2
[12.22.2020_15-51-43] Running chmod 640 /usr/local/lscp/cyberpanel/logs/access.log failed. Running again, try number 3
[12.22.2020_15-51-43] [ERROR] We are not able to run chmod 640 /usr/local/lscp/cyberpanel/logs/access.log return code: 

# ubuntu 20.04
##############
...
[12.22.2020_16-11-15] Running groupadd docker failed. Running again, try number 1
[12.22.2020_16-11-15] Running groupadd docker failed. Running again, try number 2
[12.22.2020_16-11-15] Running groupadd docker failed. Running again, try number 3
[12.22.2020_16-11-15] [ERROR] We are not able to run groupadd docker return code: 9.
...
[12.22.2020_16-12-52] (1238, "Variable 'innodb_file_format' is a read only variable"). [ERROR:335]
[12.22.2020_16-13-41] Running cp /usr/local/lsws/lsphp71/bin/php /usr/bin/ failed. Running again, try number 1
[12.22.2020_16-13-41] Running cp /usr/local/lsws/lsphp71/bin/php /usr/bin/ failed. Running again, try number 2
[12.22.2020_16-13-41] Running cp /usr/local/lsws/lsphp71/bin/php /usr/bin/ failed. Running again, try number 3
[12.22.2020_16-13-41] [ERROR] We are not able to run cp /usr/local/lsws/lsphp71/bin/php /usr/bin/ return code: 1.
[12.22.2020_16-13-43] Running apt-get -y debconf-utils failed. Running again, try number 1
[12.22.2020_16-13-43] Running apt-get -y debconf-utils failed. Running again, try number 2
[12.22.2020_16-13-43] Running apt-get -y debconf-utils failed. Running again, try number 3
[12.22.2020_16-13-43] [ERROR] We are not able to run apt-get -y debconf-utils return code: 100.
/etc/aliases does not exist, creating it.
WARNING: /etc/aliases exists, but does not have a root alias.
...
[12.22.2020_16-15-20] Running chown -R lscpd:lscpd /usr/local/CyberCP/public/phpmyadmin failed. Running again, try number 1
[12.22.2020_16-15-20] Running chown -R lscpd:lscpd /usr/local/CyberCP/public/phpmyadmin failed. Running again, try number 2
[12.22.2020_16-15-20] Running chown -R lscpd:lscpd /usr/local/CyberCP/public/phpmyadmin failed. Running again, try number 3
[12.22.2020_16-15-20] [ERROR] We are not able to run chown -R lscpd:lscpd /usr/local/CyberCP/public/phpmyadmin return code: 1
...
[12.22.2020_16-15-52] Running usermod -G lscpd,lsadm,nobody lscpd failed. Running again, try number 1
[12.22.2020_16-15-52] Running usermod -G lscpd,lsadm,nobody lscpd failed. Running again, try number 2
[12.22.2020_16-15-52] Running usermod -G lscpd,lsadm,nobody lscpd failed. Running again, try number 3
[12.22.2020_16-15-52] [ERROR] We are not able to run usermod -G lscpd,lsadm,nobody lscpd return code: 6.
[12.22.2020_16-15-58] Running chmod 644 /etc/yum.repos.d/MariaDB.repo failed. Running again, try number 1
[12.22.2020_16-15-58] Running chmod 644 /etc/yum.repos.d/MariaDB.repo failed. Running again, try number 2
[12.22.2020_16-15-58] Running chmod 644 /etc/yum.repos.d/MariaDB.repo failed. Running again, try number 3
[12.22.2020_16-15-58] [ERROR] We are not able to run chmod 644 /etc/yum.repos.d/MariaDB.repo return code: 1.
[12.22.2020_16-15-58] Running chmod 644 /etc/pdns/pdns.conf failed. Running again, try number 1
[12.22.2020_16-15-58] Running chmod 644 /etc/pdns/pdns.conf failed. Running again, try number 2
[12.22.2020_16-15-58] Running chmod 644 /etc/pdns/pdns.conf failed. Running again, try number 3
[12.22.2020_16-15-58] [ERROR] We are not able to run chmod 644 /etc/pdns/pdns.conf return code: 1.
[12.22.2020_16-15-58] Running chmod 644 /usr/local/lsws/conf/httpd_config.xml failed. Running again, try number 1
[12.22.2020_16-15-58] Running chmod 644 /usr/local/lsws/conf/httpd_config.xml failed. Running again, try number 2
[12.22.2020_16-15-58] Running chmod 644 /usr/local/lsws/conf/httpd_config.xml failed. Running again, try number 3
[12.22.2020_16-15-58] [ERROR] We are not able to run chmod 644 /usr/local/lsws/conf/httpd_config.xml return code: 1.
[12.22.2020_16-15-58] Running chmod 644 /usr/local/lsws/conf/modsec.conf failed. Running again, try number 1
[12.22.2020_16-15-58] Running chmod 644 /usr/local/lsws/conf/modsec.conf failed. Running again, try number 2
[12.22.2020_16-15-58] Running chmod 644 /usr/local/lsws/conf/modsec.conf failed. Running again, try number 3
[12.22.2020_16-15-58] [ERROR] We are not able to run chmod 644 /usr/local/lsws/conf/modsec.conf return code: 1.
[12.22.2020_16-15-58] Running chmod 644 /usr/local/lsws/conf/httpd.conf failed. Running again, try number 1
[12.22.2020_16-15-58] Running chmod 644 /usr/local/lsws/conf/httpd.conf failed. Running again, try number 2
[12.22.2020_16-15-58] Running chmod 644 /usr/local/lsws/conf/httpd.conf failed. Running again, try number 3
[12.22.2020_16-15-58] [ERROR] We are not able to run chmod 644 /usr/local/lsws/conf/httpd.conf return code: 1.
[12.22.2020_16-15-59] Running chmod 600 /etc/pdns/pdns.conf failed. Running again, try number 1
[12.22.2020_16-15-59] Running chmod 600 /etc/pdns/pdns.conf failed. Running again, try number 2
[12.22.2020_16-15-59] Running chmod 600 /etc/pdns/pdns.conf failed. Running again, try number 3
[12.22.2020_16-15-59] [ERROR] We are not able to run chmod 600 /etc/pdns/pdns.conf return code: 1.
[12.22.2020_16-15-59] Running chmod 600 /etc/cagefs/exclude/cyberpanelexclude failed. Running again, try number 1
[12.22.2020_16-15-59] Running chmod 600 /etc/cagefs/exclude/cyberpanelexclude failed. Running again, try number 2
[12.22.2020_16-15-59] Running chmod 600 /etc/cagefs/exclude/cyberpanelexclude failed. Running again, try number 3
[12.22.2020_16-15-59] [ERROR] We are not able to run chmod 600 /etc/cagefs/exclude/cyberpanelexclude return code: 1.
[12.22.2020_16-15-59] Running chmod 640 /usr/local/lscp/cyberpanel/logs/access.log failed. Running again, try number 1
[12.22.2020_16-15-59] Running chmod 640 /usr/local/lscp/cyberpanel/logs/access.log failed. Running again, try number 2
[12.22.2020_16-15-59] Running chmod 640 /usr/local/lscp/cyberpanel/logs/access.log failed. Running again, try number 3
[12.22.2020_16-15-59] [ERROR] We are not able to run chmod 640 /usr/local/lscp/cyberpanel/logs/access.log return code: 1.
```

**Comment by rylabs-billy** [comment]
Similar with CentOS 7/8 but I didn't include them here since they will be deprecating.

**Comment by Code-Egg** [comment]
Hi @rylabs-billy,
May I know if you are running as a root user? not sudo.

**Comment by rylabs-billy** [comment]
Hi @Code-Egg ,
Yeah the StackScript is running as root user.

**Comment by Code-Egg** [comment]
Hi, @rylabs-billy , 

Tested and confirmed, those messages can be safely ignored.

**Comment by rylabs-billy** [comment]
Hi @Code-Egg,

Hope you are well. The welcome banner after install states the following:
```
On the server:
* You can get the CyberPanel admin password with the following command:
sudo cat /home/ubuntu/.litespeed_password
* You can get the Mysql cyberpanel user password with the following command:
sudo cat /home/ubuntu/.db_password
```
However because the script is run as `root`, the real paths are:
```
/root/.litespeed_password
/root/.db_password
```
This appears to be same script used for the other Cloud providers, so if it's not ideal to update the core [per-instance.sh](https://github.com/litespeedtech/ls-cloud-image/blob/master/Cloud-init/per-instance.sh), could you make a Linode specific `instance.sh` and banner?

We are working on releasing this in the upcoming cycle and putting together documentation, so just trying to iron out the final pieces. The updated banner will be better for our [documentation](https://www.linode.com/docs/).

**Comment by Code-Egg** [comment]
Thanks for checking, it should be fixed.

**Pull request merged**
