### PR TITLE
Add Easypanel

### PR DESCRIPTION
**Pull request by deiucanta**
Hey Linode, this is my submission for Easypanel to Linode Marketplace. Let me know if there are any changes required in order to get this approved.

### CODE REVIEW

**Comment by deiucanta** [comment]
@hmorris3293 is there anything else I need to do to get this PR approved?

**Comment by maddiepresland** [comment]
> @hmorris3293 is there anything else I need to do to get this PR approved?

Hey @deiucanta! Thanks for the submission - it can take a few weeks for us to test the app and provide feedback, but it's on our radar.

**Comment by deiucanta** [comment]
@maddiepresland is there anything I can do to expedite the process?

**Comment by hmorris3293** [comment]
All is Approved! Tentative release is set for May 31st

**Pull request merged**
